/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpesaRouteImport } from './routes/spesa'
import { Route as RicetteRouteImport } from './routes/ricette'
import { Route as PrezziRouteImport } from './routes/prezzi'
import { Route as DispensaRouteImport } from './routes/dispensa'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RicetteIdRouteImport } from './routes/ricette.$id'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const SpesaRoute = SpesaRouteImport.update({
  id: '/spesa',
  path: '/spesa',
  getParentRoute: () => rootRouteImport,
} as any)
const RicetteRoute = RicetteRouteImport.update({
  id: '/ricette',
  path: '/ricette',
  getParentRoute: () => rootRouteImport,
} as any)
const PrezziRoute = PrezziRouteImport.update({
  id: '/prezzi',
  path: '/prezzi',
  getParentRoute: () => rootRouteImport,
} as any)
const DispensaRoute = DispensaRouteImport.update({
  id: '/dispensa',
  path: '/dispensa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RicetteIdRoute = RicetteIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RicetteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dispensa': typeof DispensaRoute
  '/prezzi': typeof PrezziRoute
  '/ricette': typeof RicetteRouteWithChildren
  '/spesa': typeof SpesaRoute
  '/api/chat': typeof ApiChatRoute
  '/ricette/$id': typeof RicetteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dispensa': typeof DispensaRoute
  '/prezzi': typeof PrezziRoute
  '/ricette': typeof RicetteRouteWithChildren
  '/spesa': typeof SpesaRoute
  '/api/chat': typeof ApiChatRoute
  '/ricette/$id': typeof RicetteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dispensa': typeof DispensaRoute
  '/prezzi': typeof PrezziRoute
  '/ricette': typeof RicetteRouteWithChildren
  '/spesa': typeof SpesaRoute
  '/api/chat': typeof ApiChatRoute
  '/ricette/$id': typeof RicetteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dispensa'
    | '/prezzi'
    | '/ricette'
    | '/spesa'
    | '/api/chat'
    | '/ricette/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dispensa'
    | '/prezzi'
    | '/ricette'
    | '/spesa'
    | '/api/chat'
    | '/ricette/$id'
  id:
    | '__root__'
    | '/'
    | '/dispensa'
    | '/prezzi'
    | '/ricette'
    | '/spesa'
    | '/api/chat'
    | '/ricette/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DispensaRoute: typeof DispensaRoute
  PrezziRoute: typeof PrezziRoute
  RicetteRoute: typeof RicetteRouteWithChildren
  SpesaRoute: typeof SpesaRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spesa': {
      id: '/spesa'
      path: '/spesa'
      fullPath: '/spesa'
      preLoaderRoute: typeof SpesaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ricette': {
      id: '/ricette'
      path: '/ricette'
      fullPath: '/ricette'
      preLoaderRoute: typeof RicetteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prezzi': {
      id: '/prezzi'
      path: '/prezzi'
      fullPath: '/prezzi'
      preLoaderRoute: typeof PrezziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispensa': {
      id: '/dispensa'
      path: '/dispensa'
      fullPath: '/dispensa'
      preLoaderRoute: typeof DispensaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ricette/$id': {
      id: '/ricette/$id'
      path: '/$id'
      fullPath: '/ricette/$id'
      preLoaderRoute: typeof RicetteIdRouteImport
      parentRoute: typeof RicetteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RicetteRouteChildren {
  RicetteIdRoute: typeof RicetteIdRoute
}

const RicetteRouteChildren: RicetteRouteChildren = {
  RicetteIdRoute: RicetteIdRoute,
}

const RicetteRouteWithChildren =
  RicetteRoute._addFileChildren(RicetteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DispensaRoute: DispensaRoute,
  PrezziRoute: PrezziRoute,
  RicetteRoute: RicetteRouteWithChildren,
  SpesaRoute: SpesaRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
